import * as vscode from 'vscode';
import { TypeScriptCustomEditorProvider } from './customEditorProvider';
import { DtsGenerator } from './dtsGenerator';

export function activate(context: vscode.ExtensionContext) {
  // Register the custom editor provider for .js files
  const customEditorProvider = new TypeScriptCustomEditorProvider();
  const providerRegistration = vscode.window.registerCustomEditorProvider(
    'tMinusTS.typescriptEditor',
    customEditorProvider,
    {
      webviewOptions: {
        retainContextWhenHidden: true
      }
    }
  );

  // Generate .d.ts files on save (if enabled)
  const dtsGenerator = new DtsGenerator();
  vscode.workspace.onDidSaveTextDocument(async (document) => {
    if (document.languageId === 'javascript' && document.uri.scheme === 'file') {
      const config = vscode.workspace.getConfiguration('tMinusTS');
      const autoGenerate = config.get<boolean>('autoGenerateDts', false);

      if (autoGenerate) {
        await dtsGenerator.generateDtsFile(document);
      }
    }
  });

  context.subscriptions.push(providerRegistration);
}

export function deactivate() {
  // Cleanup if needed
}

